# Generated by Django 5.2.12 on 2026-03-30 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='restock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DoseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_name', models.CharField(max_length=50)),
                ('dose_date', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('birthdate', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('incident_date', models.CharField(max_length=100)),
                ('injury_type', models.CharField(max_length=50)),
                ('animal_type', models.CharField(max_length=50)),
                ('animal_owner', models.CharField(max_length=100)),
                ('animal_vaccinated', models.CharField(max_length=20)),
                ('body_part', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=200)),
                ('administered_by', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.patient')),
            ],
        ),
    ]
