# Generated by Django 5.2.12 on 2026-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vaccine_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='restock',
        ),
        migrations.AddField(
            model_name='stocklevelreport',
            name='period_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccineusagereport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doseschedule',
            name='dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocklevelreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
