# Generated by Django 5.2.12 on 2026-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_vaccine_min_stock_remove_vaccine_restock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
