# Generated by Django 5.2.12 on 2026-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_patient_role_alter_vaccine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
