# Generated by Django 5.2.12 on 2026-03-31 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_patient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='api.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccineusagereport',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_reports', to='api.vaccine'),
        ),
    ]
