# Generated by Django 5.2.10 on 2026-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_supplier_rename_vaccinationrecord_vaccinationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
