# Generated by Django 5.2.13 on 2026-04-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registration_queue_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineorder',
            old_name='price_per_dose',
            new_name='price_per_piece',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='vaccineorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccineorder',
            name='vaccine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VaccineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('available', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('ml_recommended', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.vaccine')),
            ],
        ),
    ]
